---
title: "Illustration scenario A,B,E & F"
author: "Joukje Willemsen"
date: "14-05-20"
output: html_document
---

In this file, control groups are simulated for scenario A, B, E1-3 and F1-3 to illustrate the difference in survival curves

```{r setup, include=FALSE}
load("C://Users//Joukje//Documents//GitHub//ResearchRepository//3.SimulationStudy//0.DataPreperation_output//0.Historicaldata.Rdata")

load("C://Users//Joukje//Documents//GitHub//ResearchRepository//3.SimulationStudy//0.DataPreperation_output//0.Parameters.Rdata")

load("C://Users//Joukje//Documents//GitHub//ResearchRepository//3.SimulationStudy//0.DataPreperation_output//0.HRcont_exp.Rdata")
```


#Function to simulate Time Until Mortality
```{r}
TimeUntilMortality <- function(shapeparameter = parameters$shape,scaleparameter,treatmenteffect = HR, allocation,sdrandomeffectcluster, Tmax = 548, pcont = 0.5, N = SampleSize)
  
  {
#Make 3 groups:
# 0 controlgroup
# 1 exp group where HR = HR
# 2 exp group where HR = 1

Data <- as.data.frame(c(rep.int(0, pcont*N), rep.int(1, (1-pcont)*N),rep.int(2, (1-pcont)*N)))
colnames(Data)<-"allocation"
Data$effectgroup <- ifelse(Data$allocation == 1, 1, 0) #indicate whether an effect should be simulated (only by allocation = 1)

#Generate random effect cluster
Data$randomeffectcluster <- rnorm(1, mean = 0, sd = sdrandomeffectcluster)

#Time until mortality
Data$TUM <- Data %>% 
               nrow() %>% 
               rweibull(shapeparameter,scaleparameter*exp(-(Data$effectgroup*treatmenteffect+
                 Data$randomeffectcluster)/shapeparameter))

#Censoring indicator
Data$censoring <- base::ifelse(Data$TUM>Tmax, yes = 1, no = 0)
Data$survivalcensored <- base::ifelse(Data$TUM>Tmax, yes = Tmax, no = Data$TUM)

#Status indicator
Data$StatusIndicator <- base::ifelse(Data$TUM>Tmax, yes=0, no = 1) 

return(Data)
}
```

#Input for the different scenarios
Set different parameters (see researchreport)
```{r}
shapeparameter = c(parameters$shape, (parameters$shape+0.1*parameters$shape), (parameters$shape+0.2*parameters$shape), (parameters$shape+0.3*parameters$shape), (parameters$shape+0.4*parameters$shape))
scaleparameter = c(parameters$scale, parameters$scale+100) #HR=c(1, 1.128719)
treatmenteffect = HR #the HR used in 0.DataPreperation to calculate the sample size
sdrandomeffectcluster = 0
```

```{r}
library("ggplot2")
library("survival")
library("survminer")

set.seed(123)

#Simulate scenario A
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[1], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[1], N=4000)
#controlgroup only
control11 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario B
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[1], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[2], N=4000)
#controlgroup only
control12 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario E1
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[1], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[3], N=4000)
#controlgroup only
control13 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario E2
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[1], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[4], N=4000)
#controlgroup only
control14 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario C13
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[2], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[1], N=4000)
#controlgroup only
control21 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario D1
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[2], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[2], N=4000)
#controlgroup only
control22 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario D2
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[2], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[3], N=4000)
#controlgroup only
control23 <- controlAT[which(controlAT$allocation==0),]

#Simulate scenario D3
controlAT <- TimeUntilMortality(scaleparameter = scaleparameter[2], sdrandomeffectcluster = 0, shapeparameter = shapeparameter[4], N=4000)
#controlgroup only
control24 <- controlAT[which(controlAT$allocation==0),]

#make survfit objects
Historical <- survfit( Surv(STIME18, STATUS18) ~ 1, data = Dcontrol)
control11 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control11)
control12 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control12)
control13 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control13)
control14 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control14)
control21 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control21)
control22 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control22)
control23 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control23)
control24 <- survfit( Surv(survivalcensored, StatusIndicator) ~ 1, data = control24)


#Combine the two survival curves on one graph:
fit<-list(Historical = Historical, control11 = control11, ontrol14=control14, control21=control21, control24=control24)
```

#plot survivalcurves
```{r}
plot <- ggsurvplot(fit, combine = TRUE, # Combine curves
           surv.median.line = "hv", # Add medians survival
           risk.table = FALSE,                  # Add risk table
           conf.int = FALSE,                    # Add confidence interval
           pval = FALSE,                        # Add p-value and tervals
           #conf.int.style = "step",            # CI style, use "step" or "ribbon"
           censor = FALSE,                     # Remove censor points
           tables.theme = theme_cleantable(),  # Clean risk table
           legend.title = "",                  # Change legends: title & labels
           legend.labs = c("Historical","Scenario A", "Scenario B", "Scenario E", "Scenario F"),
           linetype = c(1,2,2,3,3),
           size = 2,
           palette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"),
           ylim = c(0.5, 1),
           xlim = c(0, 548),
           xlab = "Time (in days)",
           font.x = 15,
           font.y = 15,
           font.legend = 10)
            
           #ggtheme = theme_bw() # Change ggplot2 theme
plot
```


#Save plot
```{r}
library(ggplot2)
ggsave("C:Users/Joukje/Documents/GitHub/ResearchRepository/2.Supplemental_figures/ScenarioABEF.png", plot = print(plot), width = 15, height = 10, units = "cm")

```

