---
title: "Untitled"
author: "Joukje Willemsen"
date: "14 mei 2020"
output: html_document
---

In this file, four plots are plotted to illustrate the differences of scenario A, B, C and E.

#load packages
```{r}
library(ggplot2)
```

Scenario A
```{r}
#specify lambda c, lambda h and lambda e for scenario A
lambda_cA = 0
lambda_h = 0
lambda_eA = 0

#make datasets that represent data in scenario A
x = seq(-5,5,0.01)

dataA <- rbind(
  data.frame(
    group="hist",
    x=x,
    y=dnorm(x, lambda_h, 1),
    lambda = lambda_h),
  data.frame(
    group="current",
    x=x,
    y=dnorm(x, lambda_cA, 1),
    lambda = lambda_cA),
  data.frame(
    group="exp",
    x=x,
    y=-dnorm(x, lambda_eA, 1),
    lambda = lambda_eA))

# start plot
A=ggplot(data = dataA, aes(x=x,y=y, group=group)) +
  
  scale_color_manual(values = c("#999999", "#56B4E9", "#009E73"), name = "") + #specify colours

  geom_segment(aes(x = lambda_h, y = 0, xend = 0, yend = dnorm(lambda_h)), color="#999999") + #plot historical dataset
  
  annotate("text", x = 0, y = dnorm(lambda_h)+0.06, label = expression(lambda*"h"), color="#999999") + #annotate historical plot
  
  geom_segment(aes(x = lambda_cA, y = 0, xend = lambda_cA, yend = dnorm(lambda_cA, mean = lambda_cA, sd=1)), color="#56B4E9")+ #plot control dataset
  
  annotate("text", x = 0, y = dnorm(lambda_cA)+0.02, label = expression(lambda*"c"), color="#56B4E9") + #annotate control plot
  
  geom_segment(aes(x = lambda_eA, y = 0, xend = lambda_eA, yend = -dnorm(lambda_eA, mean = lambda_eA, sd=1)), color="#009E73")+ #plot experimental dataset
  
  annotate("text", x = 0, y = - dnorm(lambda_eA) - 0.04, label = expression(lambda*"e"), color="#009E73") + #annotate experimental plot
  
  #fill the plots
  geom_area(
    aes(fill=group),
    alpha=0.2,
    position="dodge") +

  #add legend
  geom_line(aes(color=group))+
  
  scale_fill_manual(values = c("#999999", "#56B4E9", "#009E73"), name = "") +
  
  #remove breaks
  scale_x_continuous("", breaks=c()) + 
  scale_y_continuous("", breaks=c()) +
  theme_bw()

#Plot A
A
```

Scenario B
```{r}
library(ggplot2)
#specify lambdas for scenario B
lambda_cB = 2
lambda_h = 0
lambda_eB = 2


#make dataset to represent data in scenario B
x=seq(-5,5,0.01)

dataB <- rbind(
  data.frame(
    group="hist",
    x = x,
    y=dnorm(x, lambda_h, 1),
    lambda = lambda_h),
  data.frame(
    group="current",
    x= x,
    y=dnorm(x, lambda_cB, 1),
    lambda = lambda_cB),
  data.frame(
    group="exp",
    x= x,
    y=-dnorm(x, lambda_eB, 1),
    lambda = lambda_eB))

B=ggplot(dataB, aes(x=x,y=y, group=group)) +
  scale_color_manual(values = c("#999999", "#56B4E9", "#009E73"), name = "") + #specify colours

  geom_segment(aes(x = lambda_h, y = 0, xend = 0, yend = dnorm(lambda_h)), color="#999999") + #hist dataset
  
  annotate("text", x = lambda_h, y = dnorm(lambda_h, mean = lambda_h, sd = 1)+0.04, label = expression(lambda*"h"), color="#999999") + #annoate hist dataset
  
  geom_segment(aes(x = lambda_cB, y = 0, xend = lambda_cB, yend = dnorm(lambda_cB, mean = lambda_cB, sd=1)), color="#56B4E9")+ #control dataset
  
  annotate("text", x = lambda_cB, y = dnorm(lambda_cB, mean = lambda_cB, sd = 1)+0.04, label = expression(lambda*"c"), color="#56B4E9") + #annotate control dataset
  
  geom_segment(aes(x = lambda_eB, y = 0, xend = lambda_eB, yend = -dnorm(lambda_eB, mean = lambda_eB, sd=1)), color="#009E73")+ #exp dataset
  
  annotate("text", x = lambda_eB, y = - dnorm(lambda_eB, mean = lambda_eB, sd = 1) - 0.04, label = expression(lambda*"e"), color="#009E73") + #annotate exp dataset
    
  #fill the plots
  geom_area(
    aes(fill=group),
    alpha=0.2,
    position="dodge") +

  #add legend
  geom_line(aes(color=group))+
  
  scale_fill_manual(values = c("#999999", "#56B4E9", "#009E73"), name = "") +
  
  #remove breaks
  scale_x_continuous("", breaks=c()) + 
  scale_y_continuous("", breaks=c()) +
  theme_bw()

#Plot B
B
```

Scenario C
```{r}
#specify average lambda's
lambda_cC = 0
lambda_h = 0
lambda_eC = 0

#specify the lamda's of the subgroups
lambda_cC1 = -2
lambda_cC2 = -1
lambda_cC3 = 0
lambda_cC4 = 1
lambda_cC5 = 2

lambda_eC1 = -2
lambda_eC2 = -1
lambda_eC3 = 0
lambda_eC4 = 1
lambda_eC5 = 2

#Make dataset data c
dataC <- rbind(
  data.frame(
    niveau="pophist",
    group="hist",
    x=seq(-5,5,0.01),
    y=5*dnorm(x, lambda_h, 1.7),
    lambda = lambda_h),
  data.frame(
    niveau="popcont",
    group="current",
    x=seq(-5,5,0.01),
    y=5*dnorm(x, lambda_cC, 1.7),
    lambda = lambda_cC),
  data.frame(
    niveau="popexp",
    group="exp",
    x=seq(-5,5,0.01),
    y=-5*dnorm(x, lambda_eC, 1.7),
    lambda = lambda_eC),
  data.frame(
    niveau="exp",
    group="lambda_eC1",
    x=seq(-5,5,0.01),
    y=-dnorm(x, lambda_eC1, 1),
    lambda = lambda_eC1),
  data.frame(
    niveau="exp",
    group="lambda_eC2",
    x=seq(-5,5,0.01),
    y=-dnorm(x, lambda_eC2, 1),
    lambda = lambda_eC2),
  data.frame(
    niveau="exp",
    group="lambda_eC3",
    x=seq(-5,5,0.01),
    y=-dnorm(x, lambda_eC3, 1),
    lambda = lambda_eC3),
  data.frame(
    niveau="exp",
    group="lambda_eC4",
    x=seq(-5,5,0.01),
    y=-dnorm(x, lambda_eC4, 1),
    lambda = lambda_eC4),
  data.frame(
    niveau="exp",
    group="lambda_eC5",
    x=seq(-5,5,0.01),
    y=-dnorm(x, lambda_eC5, 1),
    lambda = lambda_eC5),
  data.frame(
    niveau="current",
    group="lambda_cC1",
    x=seq(-5,5,0.01),
    y=dnorm(x, lambda_cC1, 1),
    lambda = lambda_cC1),
  data.frame(
    niveau="current",
    group="lambda_cC2",
    x=seq(-5,5,0.01),
    y=dnorm(x, lambda_cC2, 1),
    lambda = lambda_cC2),
  data.frame(
    niveau="current",
    group="lambda_cC3",
    x=seq(-5,5,0.01),
    y=dnorm(x, lambda_cC3, 1),
    lambda = lambda_cC3),
  data.frame(
    niveau="current",
    group="lambda_cC4",
    x=seq(-5,5,0.01),
    y=dnorm(x, lambda_cC4, 1),
    lambda = lambda_cC4),
  data.frame(
    niveau="current",
    group="lambda_cC5",
    x=seq(-5,5,0.01),
    y=dnorm(x, lambda_cC5, 1),
    lambda = lambda_cC5))

#make dataframe subgroups control data
lambda_cClist <- 
  rbind(
    data.frame(name = lambda_cC1,
               mean = -2),
    data.frame(name = lambda_cC2,
               mean = -1),
    data.frame(name = lambda_cC3,
               mean = 0),
    data.frame(name = lambda_cC4,
               mean = 1),
    data.frame(name = lambda_cC5,
               mean = 2))

#make dataframe subgroups experimental data
lambda_eClist <- 
  rbind(
    data.frame(name = lambda_eC1,
               mean = -2),
    data.frame(name = lambda_eC2,
               mean = -1),
    data.frame(name = lambda_eC3,
               mean = 0),
    data.frame(name = lambda_eC4,
               mean = 1),
    data.frame(name = lambda_eC5,
               mean = 2))

C=ggplot(data=dataC, aes(x=x,y=y, group=group)) +
  
  scale_color_manual(values = c("#999999", "#56B4E9", "#009E73", "#009E73", "#56B4E9"), name = "") + #rood #009E73 blauw #009E73 blauw
  
  ## add lines & fillings
  
  geom_segment(aes(x = lambda_h, y = 0, xend = 0, yend = 5*dnorm(lambda_h, mean=lambda_h, sd=1.7)), color="#999999") + #hist
  
  annotate("text", x = lambda_h, y = 0.3+5*dnorm(lambda_h, mean = lambda_h, sd = 1.7), label = expression(lambda*"h"), color="#999999") +
  
  geom_segment(aes(x = lambda_cC, y = 0, xend = lambda_cC, yend = -5*dnorm(lambda_cC, mean = lambda_cC, sd=1.7)), color="#009E73")+ #hist
  
  annotate("text", x = lambda_eC, y = -0.08 + -5*dnorm(lambda_eC, mean = lambda_eC, sd = 1.7), label = expression(lambda*"e"), color="#009E73") +
  
  geom_segment(aes(x = lambda_eC, y = 0, xend = lambda_eC, yend = 5*dnorm(lambda_eC, mean = lambda_eC, sd=1.7)), color="#56B4E9") + 
  
  annotate("text", x = lambda_cC, y = 0.07+5*dnorm(lambda_cC, mean = lambda_cC, sd = 1.7), label = expression(lambda*"c"), color="#56B4E9") +
  
  
  ### annotate smaller c's ###
  
  #1
  geom_segment(aes(x = lambda_eClist$mean[1], y = 0, xend = lambda_eClist$mean[1], yend = -dnorm(lambda_eClist$mean[1], mean = lambda_eClist$mean[1], sd=1)), color="#009E73")+ #exp
  annotate("text", x = lambda_eClist$mean[1], y = -0.08 - dnorm(lambda_eClist$mean[1], mean = lambda_eClist$mean[1], sd = 1), label = expression(lambda*"e1"), color="#009E73") +
  
  #2
  geom_segment(aes(x = lambda_eClist$mean[2], y = 0, xend = lambda_eClist$mean[2], yend = -dnorm(lambda_eClist$mean[2], mean = lambda_eClist$mean[2], sd=1)), color="#009E73")+ #exp
  annotate("text", x = lambda_eClist$mean[2], y = -0.08 - dnorm(lambda_eClist$mean[2], mean = lambda_eClist$mean[2], sd = 1), label = expression(lambda*"e2"), color="#009E73") +
  
  #3
  geom_segment(aes(x = lambda_eClist$mean[3], y = 0, xend = lambda_eClist$mean[3], yend = -dnorm(lambda_eClist$mean[3], mean = lambda_eClist$mean[3], sd=1)), color="#009E73")+ #exp
  annotate("text", x = lambda_eClist$mean[3], y = -0.08 - dnorm(lambda_eClist$mean[3], mean = lambda_eClist$mean[3], sd = 1), label = expression(lambda*"e3"), color="#009E73") +
  
  #4
  geom_segment(aes(x = lambda_eClist$mean[4], y = 0, xend = lambda_eClist$mean[4], yend = -dnorm(lambda_eClist$mean[4], mean = lambda_eClist$mean[4], sd=1)), color="#009E73")+ #exp
  annotate("text", x = lambda_eClist$mean[4], y = -0.08 - dnorm(lambda_eClist$mean[4], mean = lambda_eClist$mean[4], sd = 1), label = expression(lambda*"e4"), color="#009E73") +
  
  #5
  geom_segment(aes(x = lambda_eClist$mean[5], y = 0, xend = lambda_eClist$mean[5], yend = -dnorm(lambda_eClist$mean[5], mean = lambda_eClist$mean[5], sd=1)), color="#009E73")+ #exp
  annotate("text", x = lambda_eClist$mean[5], y = -0.08 - dnorm(lambda_eClist$mean[5], mean = lambda_eClist$mean[5], sd = 1), label = expression(lambda*"e5"), color="#009E73") +
  
  ### annotate smaller e's ###
  
  #1
  geom_segment(aes(x = lambda_cClist$mean[1], y = 0, xend = lambda_cClist$mean[1], yend = dnorm(lambda_cClist$mean[1], mean = lambda_cClist$mean[1], sd=1)), color="#56B4E9")+ #exp
  annotate("text", x = lambda_cClist$mean[1], y = +0.08 + dnorm(lambda_cClist$mean[1], mean = lambda_cClist$mean[1], sd = 1), label = expression(lambda*"c1"), color="#56B4E9") +
  
  #2
  geom_segment(aes(x = lambda_cClist$mean[2], y = 0, xend = lambda_cClist$mean[2], yend = dnorm(lambda_cClist$mean[2], mean = lambda_cClist$mean[2], sd=1)), color="#56B4E9")+ #exp
  annotate("text", x = lambda_cClist$mean[2], y = +0.08 + dnorm(lambda_cClist$mean[2], mean = lambda_cClist$mean[2], sd = 1), label = expression(lambda*"c2"), color="#56B4E9") +
  
  #3
  geom_segment(aes(x = lambda_cClist$mean[3], y = 0, xend = lambda_cClist$mean[3], yend = dnorm(lambda_cClist$mean[3], mean = lambda_cClist$mean[3], sd=1)), color="#56B4E9")+ #exp
  annotate("text", x = lambda_cClist$mean[3], y = +0.08 + dnorm(lambda_cClist$mean[3], mean = lambda_cClist$mean[3], sd = 1), label = expression(lambda*"c3"), color="#56B4E9") +
  
  #4
  geom_segment(aes(x = lambda_cClist$mean[4], y = 0, xend = lambda_cClist$mean[4], yend = dnorm(lambda_cClist$mean[4], mean = lambda_cClist$mean[4], sd=1)), color="#56B4E9")+ #exp
  annotate("text", x = lambda_cClist$mean[4], y = +0.08 + dnorm(lambda_cClist$mean[4], mean = lambda_cClist$mean[4], sd = 1), label = expression(lambda*"c4"), color="#56B4E9") +
  
  #5
  geom_segment(aes(x = lambda_cClist$mean[5], y = 0, xend = lambda_cClist$mean[5], yend = dnorm(lambda_cClist$mean[5], mean = lambda_cClist$mean[5], sd=1)), color="#56B4E9")+ #exp
  annotate("text", x = lambda_cClist$mean[5], y = +0.08 + dnorm(lambda_cClist$mean[5], mean = lambda_cClist$mean[5], sd = 1), label = expression(lambda*"c5"), color="#56B4E9") +
  
  #add legend
  scale_fill_manual(values = c("#999999", "#FFFFFF", "#FFFFFF", "#009E73", "#56B4E9"), name = "") +
  
  scale_linetype_manual(values = c("solid", "dotted", "dotted", "solid", "solid"), name = "") +
  
  geom_area(aes(fill=niveau), alpha=0.3, position="dodge") +
  
  geom_line(aes(color=niveau, linetype=niveau))+
  
  #remove breaks
  scale_x_continuous("", breaks=c()) + 
  scale_y_continuous("", breaks=c()) +
  
  theme_bw()

  C

```


Scenario D
```{r}
 library(ggplot2)
  
# specify average lambda's
  lambda_c = 2
  lambda_h = 0
  lambda_e = 2
  
#specify the lambda's of the subgroups
  lambda_c1 = 0
  lambda_c2 = 1
  lambda_c3 = 2
  lambda_c4 = 3
  lambda_c5 = 4
  
  lambda_e1 = 0
  lambda_e2 = 1
  lambda_e3 = 2
  lambda_e4 = 3
  lambda_e5 = 4

#make a dataframe for subgroups 
  
  lambda_clist <- 
    rbind(
      data.frame(name = lambda_c1,
                 mean = lambda_c-2),
      data.frame(name = lambda_c2,
                 mean = lambda_c-1),
      data.frame(name = lambda_c3,
                 mean = lambda_c),
      data.frame(name = lambda_c4,
                 mean = lambda_c+1),
      data.frame(name = lambda_c5,
                 mean = lambda_c+2))
  
  lambda_elist <- 
    rbind(
      data.frame(name = lambda_e1,
                 mean = lambda_e-2),
      data.frame(name = lambda_e2,
                 mean = lambda_e-1),
      data.frame(name = lambda_e3,
                 mean = lambda_e),
      data.frame(name = lambda_e4,
                 mean = lambda_e+1),
      data.frame(name = lambda_e5,
                 mean = lambda_e+2))

  
  x <- seq(-5,7,0.1)
  
  dataD <- rbind(
    data.frame(
      niveau="pophist",
      group="hist",
      x=x,
      y=5*dnorm(x, lambda_h, 1.7),
      lambda = lambda_h),
    data.frame(
      niveau="popcont",
      group="current",
      x=x,
      y=5*dnorm(x, lambda_c, 1.7),
      lambda = lambda_c),
    data.frame(
      niveau="popexp",
      group="exp",
      x=x,
      y=-5*dnorm(x, lambda_e, 1.7),
      lambda = lambda_e),
    data.frame(
      niveau="exp",
      group="lambda_e1",
      x=x,
      y=-dnorm(x, lambda_e1, 1),
      lambda = lambda_e1),
    data.frame(
      niveau="exp",
      group="lambda_e2",
      x=x,
      y=-dnorm(x, lambda_e2, 1),
      lambda = lambda_e2),
    data.frame(
      niveau="exp",
      group="lambda_e3",
      x=x,
      y=-dnorm(x, lambda_e3, 1),
      lambda = lambda_e3),
    data.frame(
      niveau="exp",
      group="lambda_e4",
      x=x,
      y=-dnorm(x, lambda_e4, 1),
      lambda = lambda_e4),
    data.frame(
      niveau="exp",
      group="lambda_e5",
      x=x,
      y=-dnorm(x, lambda_e5, 1),
      lambda = lambda_e5),
    data.frame(
      niveau="current",
      group="lambda_c1",
      x=x,
      y=dnorm(x, lambda_c1, 1),
      lambda = lambda_c1),
    data.frame(
      niveau="current",
      group="lambda_c2",
      x=x,
      y=dnorm(x, lambda_c2, 1),
      lambda = lambda_c2),
    data.frame(
      niveau="current",
      group="lambda_c3",
      x=x,
      y=dnorm(x, lambda_c3, 1),
      lambda = lambda_c3),
    data.frame(
      niveau="current",
      group="lambda_c4",
      x=x,
      y=dnorm(x, lambda_c4, 1),
      lambda = lambda_c4),
    data.frame(
      niveau="current",
      group="lambda_c5",
      x=x,
      y=dnorm(x, lambda_c5, 1),
      lambda = lambda_c5))
  
  #start plot
  D=ggplot(data=dataD, aes(x=x,y=y, group=group)) +
    
    scale_color_manual(values = c("#999999", "#56B4E9", "#009E73", "#009E73", "#56B4E9"), name = "") +

    ## add lines & fillings
    
    geom_segment(aes(x = lambda_h, y = 0, xend = 0, yend = 5*dnorm(lambda_h, mean=lambda_h, sd=1.7)), color="#999999") + #hist
    
    annotate("text", x = lambda_h, y = 0.08+5*dnorm(lambda_h, mean = lambda_h, sd = 1.7), label = expression(lambda*"h"), color="#999999") +
    
    geom_segment(aes(x = lambda_c, y = 0, xend = lambda_c, yend = -5*dnorm(lambda_c, mean = lambda_c, sd=1.7)), color="#009E73")+ #hist
    
    annotate("text", x = lambda_e, y = -0.08 + -5*dnorm(lambda_e, mean = lambda_e, sd = 1.7), label = expression(lambda*"e"), color="#009E73") +
    
    geom_segment(aes(x = lambda_e, y = 0, xend = lambda_e, yend = 5*dnorm(lambda_e, mean = lambda_e, sd=1.7)), color="#56B4E9") + 
    
    annotate("text", x = lambda_c, y = 0.08+5*dnorm(lambda_c, mean = lambda_c, sd = 1.7), label = expression(lambda*"c"), color="#56B4E9") +
    
    
    ### add subgroups experimental groups ###
    
    #1
    geom_segment(aes(x = lambda_elist$mean[1], y = 0, xend = lambda_elist$mean[1], yend = -dnorm(lambda_elist$mean[1], mean = lambda_elist$mean[1], sd=1)), color="#009E73")+ #exp
    annotate("text", x = lambda_elist$mean[1], y = -0.08 - dnorm(lambda_elist$mean[1], mean = lambda_elist$mean[1], sd = 1), label = expression(lambda*"e1"), color="#009E73") +
    
    #2
    geom_segment(aes(x = lambda_elist$mean[2], y = 0, xend = lambda_elist$mean[2], yend = -dnorm(lambda_elist$mean[2], mean = lambda_elist$mean[2], sd=1)), color="#009E73")+ #exp
    annotate("text", x = lambda_elist$mean[2], y = -0.08 - dnorm(lambda_elist$mean[2], mean = lambda_elist$mean[2], sd = 1), label = expression(lambda*"e2"), color="#009E73") +
    
    #3
    geom_segment(aes(x = lambda_elist$mean[3], y = 0, xend = lambda_elist$mean[3], yend = -dnorm(lambda_elist$mean[3], mean = lambda_elist$mean[3], sd=1)), color="#009E73")+ #exp
    annotate("text", x = lambda_elist$mean[3], y = -0.08 - dnorm(lambda_elist$mean[3], mean = lambda_elist$mean[3], sd = 1), label = expression(lambda*"e3"), color="#009E73") +
    
    #4
    geom_segment(aes(x = lambda_elist$mean[4], y = 0, xend = lambda_elist$mean[4], yend = -dnorm(lambda_elist$mean[4], mean = lambda_elist$mean[4], sd=1)), color="#009E73")+ #exp
    annotate("text", x = lambda_elist$mean[4], y = -0.08 - dnorm(lambda_elist$mean[4], mean = lambda_elist$mean[4], sd = 1), label = expression(lambda*"e4"), color="#009E73") +
    
    #5
    geom_segment(aes(x = lambda_elist$mean[5], y = 0, xend = lambda_elist$mean[5], yend = -dnorm(lambda_elist$mean[5], mean = lambda_elist$mean[5], sd=1)), color="#009E73")+ #exp
    annotate("text", x = lambda_elist$mean[5], y = -0.08 - dnorm(lambda_elist$mean[5], mean = lambda_elist$mean[5], sd = 1), label = expression(lambda*"e5"), color="#009E73") +
    
    ### add subgroups control group ###
    
    #1
    geom_segment(aes(x = lambda_clist$mean[1], y = 0, xend = lambda_clist$mean[1], yend = dnorm(lambda_clist$mean[1], mean = lambda_clist$mean[1], sd=1)), color="#56B4E9")+ #exp
    annotate("text", x = lambda_clist$mean[1], y = +0.08 + dnorm(lambda_clist$mean[1], mean = lambda_clist$mean[1], sd = 1), label = expression(lambda*"c1"), color="#56B4E9") +
    
    #2
    geom_segment(aes(x = lambda_clist$mean[2], y = 0, xend = lambda_clist$mean[2], yend = dnorm(lambda_clist$mean[2], mean = lambda_clist$mean[2], sd=1)), color="#56B4E9")+ #exp
    annotate("text", x = lambda_clist$mean[2], y = +0.08 + dnorm(lambda_clist$mean[2], mean = lambda_clist$mean[2], sd = 1), label = expression(lambda*"c2"), color="#56B4E9") +
    
    #3
    geom_segment(aes(x = lambda_clist$mean[3], y = 0, xend = lambda_clist$mean[3], yend = dnorm(lambda_clist$mean[3], mean = lambda_clist$mean[3], sd=1)), color="#56B4E9")+ #exp
    annotate("text", x = lambda_clist$mean[3], y = +0.08 + dnorm(lambda_clist$mean[3], mean = lambda_clist$mean[3], sd = 1), label = expression(lambda*"c3"), color="#56B4E9") +
    
    #4
    geom_segment(aes(x = lambda_clist$mean[4], y = 0, xend = lambda_clist$mean[4], yend = dnorm(lambda_clist$mean[4], mean = lambda_clist$mean[4], sd=1)), color="#56B4E9")+ #exp
    annotate("text", x = lambda_clist$mean[4], y = +0.08 + dnorm(lambda_clist$mean[4], mean = lambda_clist$mean[4], sd = 1), label = expression(lambda*"c4"), color="#56B4E9") +
    
    #5
    geom_segment(aes(x = lambda_clist$mean[5], y = 0, xend = lambda_clist$mean[5], yend = dnorm(lambda_clist$mean[5], mean = lambda_clist$mean[5], sd=1)), color="#56B4E9")+ #exp
    annotate("text", x = lambda_clist$mean[5], y = +0.08 + dnorm(lambda_clist$mean[5], mean = lambda_clist$mean[5], sd = 1), label = expression(lambda*"c5"), color="#56B4E9") +
    
    #fill plots
    scale_fill_manual(values = c("#999999", "#FFFFFF", "#FFFFFF", "#009E73", "#56B4E9"), name = "") +
    
    #legend
    scale_linetype_manual(values = c("solid", "dotted", "dotted", "solid", "solid"), name = "") +
    
    geom_area(aes(fill=niveau), alpha=0.3, position="dodge") +
    
    geom_line(aes(color=niveau, linetype=niveau))+
    
    #remove breaks
    scale_x_continuous("", breaks=c()) + 
    scale_y_continuous("", breaks=c()) +
 
    theme_bw()
    
  D

```

Save
```{r}
# Make 1 annotated plot

arrangedfigure <- ggpubr::ggarrange(A, B, C, D, 
                                    labels = c("A", "B", "C", "D"),
                                    ncol = 2, nrow = 2, common.legend = TRUE)

annotatedfigure <- ggpubr::annotate_figure(arrangedfigure, 
                                           top = ggpubr::text_grob(expression(paste(lambda["c"]," = ", lambda["h"],"                 ", lambda["c"]," > ", lambda["h"])), face = "bold", size = 15), 
                                           left = ggpubr::text_grob(expression(paste(sigma["s"]," > 0                      ", sigma["s"], " = 0")), face = "bold", size = 15, rot = 90))

library(ggplot2)
ggsave("4.ScenarioABCD.png", plot = annotatedfigure, width = 7, height = 5)

```






